## workflow set up
# working output dir
predir: '/media/storage/wes2_output/'
# source dir for supporting scripts
srcdir: '/home/pendletonmr_nih_gov/p/cidc_wes2/source'
# file to write running log
log_file: '/media/storage//wes2_output/pipeline.log'
# number of CPU cores dedicated to entire workflow
ncores: 60


## output file paths layout file
file_layout: 'config/file_layout.yaml'


## reference genome download locations file
reference: 'config/reference_dev.csv'


## sample metadata file
sample_metadata: 'config/sample_metadata_dev.csv'

## sample pairing data
## to be used in the future once we're building the tumor normal vs tumor only bits.
pairings: "config/pairings.csv"


## preprocess options
quality_trim: '20'


## cloud program [gsutil, aws] and bucket location
cloud_prog: 'gsutil'
archive_bucket: ''

## sentieon path
## The realigner and recalibration tools in old wes are from `sentieon driver`
## and the documentation isn't immediately clear about the identity
## of the underlying algorithms. Algos in re-alignment vary in accuracy, so
## for now this step will be written using sentieon, but might be re-written
## using something like DeepVariant.
sentieon_path: "/media/storage/sentieon/sentieon-genomics-202112.06/bin/"

## GATK Picard MarkDuplicatesSpark
mem: 64000 ## Amount of memory in megabytes that needs to be available in order for the job to initiate

## HLA-HD
hlahd:
  path: "hlahd.1.7.0/bin/"
  min_length: 50 #hla-hd param -m which sets the min read length- fixed b/c we don't expect any libraries with shorter than 50bp
  cut_percent: 0.95 #hla-hd param -c, if mistmatch how much to cut back

### optitype information
optitype:
  config: "config/optitype.config.ini"

###VEP settings
vep:
  species: "Homo sapiens"
  build: "GRCh38.p14"
  release: "111"
