## INITIALIZE
genome:
    fa: "GCA_000001405.15_GRCh38_full_analysis_set.fna" 
    bwt: "GCA_000001405.15_GRCh38_full_analysis_set.fna.bwt" 
    size: "genome.size"
    fai: "GCA_000001405.15_GRCh38_full_analysis_set.fna.fai"
    blacklist: "hg38-blacklist.v2.bed"
    filtered_fai: "GCA_000001405.15_GRCh38_no_alt_analysis_set_filtered.fna.fai"
    bed: "GCA_000001405.15_GRCh38_no_alt_analysis_set_filtered.bed"
    dhs: "DHS_hg38.bed"

    mills: "Mills_and_1000G_gold_standard.indels.hg38.vcf.bgz"
    mills_index: "Mills_and_1000G_gold_standard.indels.hg38.vcf.bgz.tbi"
    g1000: "1000G_phase1.snps.high_confidence.hg38.vcf.bgz"
    g1000_index: "1000G_phase1.snps.high_confidence.hg38.vcf.bgz.tbi"
    dbsnp: "00-All_fixed.vcf.bgz"    
    dbsnp_index: "00-All_fixed.vcf.bgz.tbi"    
    hla_bed: "hla.bed"
    hla_tsv: "hla.tsv"
    hla_fna: "hla.fna"
    hla_dmnd: "hla.dmnd"
    hla_faa: "hla.faa"
    hla_shift: "hla.shift"
    hla_freq: "hla.freq"
    picard_dict": "GCA_000001405.15_GRCh38_full_analysis_set.dict"
    coverage_targets: "gencode27.canonical.bed"

    
annot:
    gtf: "GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gtf"
    bed: "GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.bed"
    bw: "hg38.phastCons100way.bw"
    
## INGEST
input:
    input_fastq: "{{sample}}_{read}.fastq.gz"
    input_bam: "{sample}_input.bam"
cutadapt:
    cutadapt_fastq: "{{sample}}_{read}"
rqual_filter:
    qfilter_fastq_single: "{{sample}}_{read}_qual.fastq.gz"
    qfilter_fastq_paired: "{{sample}}_{read}{paired}_qual.fastq.gz"

hlahd:
    report: "{sample}.final_report.txt"

## CONTAMINATION
centrifuge:
    classification: "{sample}_classification.txt"
    report: "{sample}_report.txt"
    tar: "p_compressed+h+v.tar.gz"
    db: "p_compressed+h+v.1.cf"

## MAPPING
bam:
    bam: "{sample}.bam"
    index: "{sample}.bam.bai"
    dup_bam: "{sample}_dup.bam"
    flags_bam: "{sample}_flags.bam"
    blacklist_bam: "{sample}_blacklist.bam"
    fixmate_bam: "{sample}_fixmate.bam"
    filtered_bam: "{sample}_filtered.bam"
    filtered_index: "{sample}_filtered.bam.bai"
    filtered_chr6_bam: "{sample}_filtered.chr6.bam"
    filtered_chr6_bam_index: "{sample}_filtered.chr6.bam.bai"    
    realigned_bam: "{sample}_realigned.bam"
    realigned_index: "{sample}_realigned.bam.bai"
    metrics: "{sample}_marked_duplicates_metrics.txt"
    sampled_bam: "{sample}_sampled.bam"
    sampled_index: "{sample}_sampled.bam.bai"

rseqc:
    bamqc_txt: "{sample}_bam_qc.txt"
    bamgc_txt: "{sample}_bam_gc.txt"
    bamgc_r: "{sample}.GC_plot.r"

fastqc:
    targz: "{sample}_filtered_fastqc.tar.gz"

bqsr:
    prerecaltable: "{sample}_prerecal_data.table"
    postrecaltable: "{sample}_postrecal_data.table"    
    recal_bam: "{sample}_recalibrated.bam"
    recal_index: "{sample}_recalibrated.bam.bai"
    recal_table: "{sample}_recal.csv"
<<<<<<< HEAD
=======
    recal_round2_bam: "{sample}_recal_round2.bam"
    recal_round2_index: "{sample}_recal_round2.bam.bai"
    recal_chr6_bam: "{sample}_recalibrated_round2.chr6.bam"
    recal_chr6_index: "{sample}_recalibrated_round2.chr6.bai"
    recal_chr6_fq_r1: "{sample}_recalibrated_round2.chr6.r1.fq.gz"
    recal_chr6_fq_r2: "{sample}_recalibrated_round2.chr6.r2.fq.gz"
>>>>>>> 0e3d4df36f6c61d18617be1af077116ee5453cef

    report: "{sample}_recal.pdf"

xhla:
    report: "{sample}_hla.json"

coverage:
    depth: "{sample}_exome_coverage_depth.txt"
    bdg: "{sample}_exome_coverage.bdg"
    bw: "{sample}_exome_coverage.bw"

cnv:
    bed: "{sample}_cnv_segmented.bed"
    igv: "{sample}_cnv_segmented.igv"
    csv: "{sample}_cnv_annot.csv"

